{
 "title": "CONDITION BASED MONITORING FOR MOTOR",
 "time": { "from": "2023-03-08T15:16:48.000Z", "to": "2023-03-08T15:28:17.000Z" },
 "templating": {
  "list": [
   {
    "name": "SPEED",
    "query": "select speed as SPEED from motor_speed_current DESC LIMIT 1;\n"
   },
   {
    "name": "CURRENT",
    "query": "SELECT current_amp FROM motor_speed_current DESC LIMIT 1;"
   },
   {
    "name": "X_Vibration",
    "query": "SELECT vibration_x from motor_accelerometer;"
   },
   {
    "name": "Y_Vibration",
    "query": "select vibration_y from motor_accelerometer;"
   },
   {
    "name": "Z_Vibration",
    "query": "select vibration_z from motor_accelerometer;"
   },
   {
    "name": "Celsius",
    "query": "select temp_celsius from motor_temperature;"
   },
   {
    "name": "Fahrenheit",
    "query": "select temp_fahrenheit from motor_temperature;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#00008b\">\n   \n<a href=\"https://ibb.co/bFZgFc8\"><img src=\"https://i.postimg.cc/rz6mD3p3/ibm-logo-white-png-1.png\" alt=\"ibm-logo\" border=\"0\" width=\"120px\"></a>\n<B><label style=\"font-size: 38px;color:white;margin-left:650px; text-align:center\" for=\"html\">MACHINE RELIABILITY MONITORING & CONTROL SYSTEM FOR MOTOR 3M-22</br>\nVARIABLE SPEED MOTOR\n</label></B>\n</div>\n\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 4 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<title></title>\n<head>\n</head>\n<body>\n<div></div>\n<p>\n<h2><center><b>Live Streaming</b></center></h2>\n<video id=video src=\"http://192.168.0.106:8082\" autoplay=\"autoplay\"  width=1030 height=500/>\n</p>\n</body>\n</html>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 10, "y": 4 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<title></title>\n<head>\n</head>\n<body>\n<div></div>\n<p>\n  <b><center><h2>Reference Image</b> </h2>\n<a href='https://postimg.cc/fkXCGCM2' target='_blank'><img src='https://i.postimg.cc/fkXCGCM2/image-2.png' border='0' alt='image-2' width='750px' height='300px'/></a></br>\n</p>\n<h3><b>Date: 9th March 2023</b></h3>\n<h3><b>Failure Code: Vacuum Pump line blockage.</b></h3>\n</body>\n</html>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n \n  <h3 style=\"font-size: 40px; margin-top:40px\"><center><b>Speed &nbsp &nbsp &nbsp &nbsp &nbsp Current </br>\n  <p>${SPEED} RPM &nbsp &nbsp &nbsp &nbsp &nbsp ${CURRENT} A</p>\n         </b></center></h3>\n  </div>\n</body>\n</html>"
   }
  },
  {
   "title": "Speed Vs Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "queryText": "SELECT  speed as SPEED,TEMPERATURE_CELSIUS as TEMPERATURE_CELSIUS, (strftime('%s',timestamp)) as time from motor_speed_current;\r\n",
     "rawQueryText": "SELECT  speed as SPEED,TEMPERATURE_CELSIUS as TEMPERATURE_CELSIUS, (strftime('%s',timestamp)) as time from motor_speed_current;\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n \n  <h3 style=\"font-size: 40px; margin-top:40px\"><center><b>Temperature in ℃ &nbsp &nbsp Temperature in ℉  </br>\n  <p>${Celsius} ℃ &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp ${Fahrenheit}  ℉ </p>\n         </b></center></h3>\n  </div>\n</body>\n</html>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 16 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n \n  <h3 style=\"font-size: 40px; margin-top:45px\"><center><b>X-Vibration &nbsp &nbsp Y-Vibration &nbsp &nbsp Z-Vibration </br>\n  <p>${X_Vibration} m/s2 &nbsp &nbsp &nbsp  ${Y_Vibration}  m/s2 &nbsp &nbsp &nbsp ${Z_Vibration} m/s2</p>\n         </b></center></h3>\n  </div>\n</body>\n</html>"
   }
  },
  {
   "title": "Current Vs Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "queryText": "SELECT  Current_amp as CURRENT,TEMPERATURE_CELSIUS as TEMPERATURE_CELSIUS, (strftime('%s',timestamp)) as time from motor_speed_current;\r\n",
     "rawQueryText": "SELECT  Current_amp as CURRENT,TEMPERATURE_CELSIUS as TEMPERATURE_CELSIUS, (strftime('%s',timestamp)) as time from motor_speed_current;\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature in Celsius",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT temp_celsius as \"Temperature(Celsius)\", (strftime('%s',timestamp)) as time from motor_temperature;",
     "rawQueryText": "SELECT temp_celsius as \"Temperature(Celsius)\", (strftime('%s',timestamp)) as time from motor_temperature;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature in Fahrenheit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "queryText": "SELECT temp_fahrenheit as \"Temperature(Fahrenheit)\", (strftime('%s',timestamp)) as time from motor_temperature;",
     "rawQueryText": "SELECT temp_fahrenheit as \"Temperature(Fahrenheit)\", (strftime('%s',timestamp)) as time from motor_temperature;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Accelerometer Vibrations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "queryText": "SELECT vibration_x as \"vibration_x\",vibration_y as \"vibration_y\", vibration_z as \"vibration_z\", (strftime('%s',timestamp)) as time from motor_accelerometer;",
     "rawQueryText": "SELECT vibration_x as \"vibration_x\",vibration_y as \"vibration_y\", vibration_z as \"vibration_z\", (strftime('%s',timestamp)) as time from motor_accelerometer;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}