{
 "title": "HEALTH MONITORING SYSTEM FOR MOTOR 3M-22",
 "time": { "from": "2023-03-08T15:16:33.124Z", "to": "2023-03-08T15:27:38.922Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:#00008b\">\n   \n<a href=\"https://ibb.co/bFZgFc8\"><img src=\"https://i.ibb.co/gdpMdkB/ibm-logo.png\" alt=\"ibm-logo\" border=\"0\" width=\"120px\"></a>\n<B><label style=\"font-size: 38px;color:white;margin-left:650px; text-align:center\" for=\"html\">HEALTH MONITORING SYSTEM FOR MOTOR 3M-22\n</label></B>\n</div>\n\n\n\n"
   }
  },
  {
   "title": "Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT HEALTH FROM HEALTH_DATA;",
     "rawQueryText": "SELECT HEALTH FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Criticality",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT CRITICALITY FROM HEALTH_DATA;",
     "rawQueryText": "SELECT CRITICALITY FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Risk",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT RISK FROM HEALTH_DATA;",
     "rawQueryText": "SELECT RISK FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "End of Life",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 3 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n  <h3 style=\"font-size: 25px; margin-top:35px\"><center><b>Useful life is at</br> </br><p style=\"font-size: 40px\">44.2%</p></b></center></h3>\n  </div>\n</body>\n</html>"
   },
   "targets": [
    {
     "queryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "rawQueryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Effective Age",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 3 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n  <h3 style=\"font-size: 35px; margin-top:50px\"><center><b></br>5.6 years</b></center></h3>\n  </div>\n</body>\n</html>"
   },
   "targets": [
    {
     "queryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "rawQueryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Next PM",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 3 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n  <h3 style=\"font-size: 25px; margin-top:35px\"><center><b>Generating in</br> </br><p style=\"font-size: 40px\">14 days</p></b></center></h3>\n  </div>\n</body>\n</html>"
   },
   "targets": [
    {
     "queryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "rawQueryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MRR",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 3 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n  <h3 style=\"font-size: 25px; margin-top:35px\"><center><b>Rate is</br> </br><p style=\"font-size: 40px\">0.3%</p></b></center></h3>\n  </div>\n</body>\n</html>"
   },
   "targets": [
    {
     "queryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "rawQueryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Next Failure",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 3 },
   "options": {
    "content": "<html>\n<head>\n\n</head>\n\n<body>\n  <div>\n  <h3 style=\"font-size: 35px; margin-top:50px\"><center><b></br>331 Days</b></center></h3>\n  </div>\n</body>\n</html>"
   },
   "targets": [
    {
     "queryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "rawQueryText": "SELECT END_OF_LIFE FROM HEALTH_DATA;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": {
    "content": "\n<!DOCTYPE html>\n<html>\n\n<style>\n    table, th, td {\n            border: 5px solid black;\n            font-weight: bold;\n            font-size: 24px;\n        }\n    \n    th, td {\n  background-color: #CCCCE8;\n}\n\n</style>\n<body>\n<h2><b>Health details as of 10:21 AM on 09/03/2023</b></h2>\n<h2 style=\"margin-left:80%\"><b>Scoring group: Pumps </b></h2>\n    <table style=\"width:100%; height:197px\">\n        <tr>\n            <th>Score</th>\n            <th>Contributor</th>\n            <th>Weight</th>\n        </tr>\n        <tr>\n            <td>17</td>\n            <td>FACRULYEARSSAMPLE</td>\n            <td>60%</td>\n        </tr>\n        <tr>\n            <td>87</td>\n            <td>Open Work Orders</td>\n            <td>20%</td>\n        </tr>\n        <tr>\n            <td>25</td>\n            <td> Meter Health</td>\n            <td>20%</td>\n        </tr>   \n    </table>\n</body>\n \n</html>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": {
    "content": "\n<!DOCTYPE html>\n<html>\n\n<style>\n    table, th, td {\n            border: 5px solid black;\n            font-weight: bold;\n            font-size: 24px;\n        }\n    \n    th, td {\n  background-color: #CCCCE8;\n}\n\n</style>\n<body>\n<h2><b>Criticality details as of 10:21 AM on 10/03/2023</b></h2>\n<h2 style=\"margin-left:80%\"><b>Scoring group: Pumps </b></h2>\n    <table style=\"width:100%; height:197px\">\n        <tr>\n            <th>Score</th>\n            <th>Contributor</th>\n            <th>Weight</th>\n        </tr>\n        <tr>\n            <td>25</td>\n            <td>Priority</td>\n            <td>100%</td>\n        </tr>  \n    </table>\n</body>\n \n</html>"
   }
  },
  {
   "title": "Health History",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT HEALTH, FACRULYEARSSAMPLE, OPEN_WORK_ORDERS, METER_HEALTH,  (strftime('%s',TIMESTAMP)) as time  FROM HEALTH_HISTORY;",
     "rawQueryText": "SELECT HEALTH, FACRULYEARSSAMPLE, OPEN_WORK_ORDERS, METER_HEALTH,  (strftime('%s',TIMESTAMP)) as time  FROM HEALTH_HISTORY;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inverter Fill Function: Vacuum Pump Motor Vibration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "queryText": "SELECT XRMS_Accel, XRMS_Velocity , ZRMS_Accel, (strftime('%s',TIMESTAMP)) as time  FROM INVERTER_FILL;",
     "rawQueryText": "SELECT XRMS_Accel, XRMS_Velocity , ZRMS_Accel, (strftime('%s',TIMESTAMP)) as time  FROM INVERTER_FILL;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}